In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/AB_NYC_2024.csv",sep="\t")

In [5]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,7130382,Walter,Brooklyn,Clinton Hill,40.683710,-73.964610,Private room,55,...,20-12-2015,0.03,1,0,0,No License,5,1,1,Not specified
1,45277537,Rental unit in New York · ★4.67 · 2 bedrooms ·...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.766610,-73.988100,Entire home/apt,144,...,01-05-2023,0.24,139,364,2,No License,4.67,2,1,1
2,971353993633883038,Rental unit in New York · ★4.17 · 1 bedroom · ...,528871354,Joshua,Manhattan,Chelsea,40.750764,-73.994605,Entire home/apt,187,...,18-12-2023,1.67,1,343,6,Exempt,4.17,1,2,1
3,3857863,Rental unit in New York · ★4.64 · 1 bedroom · ...,19902271,John And Catherine,Manhattan,Washington Heights,40.835600,-73.942500,Private room,120,...,17-09-2023,1.38,2,363,12,No License,4.64,1,1,1
4,40896611,Condo in New York · ★4.91 · Studio · 1 bed · 1...,61391963,Stay With Vibe,Manhattan,Murray Hill,40.751120,-73.978600,Entire home/apt,85,...,03-12-2023,0.24,133,335,3,No License,4.91,Studio,1,1

In [6]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
20753,24736896,Rental unit in New York · ★4.75 · 1 bedroom · ...,186680487,Henry D,Manhattan,Lower East Side,40.711380,-73.991560,Private room,45,...,29-09-2023,1.81,1,157,12,No License,4.75,1,1,1
20754,2835711,Rental unit in New York · ★4.46 · 1 bedroom · ...,3237504,Aspen,Manhattan,Greenwich Village,40.730580,-74.000700,Entire home/apt,105,...,01-07-2023,0.48,1,0,1,No License,4.46,1,2,1
20755,51825274,Rental unit in New York · ★4.93 · 1 bedroom · ...,304317395,Jeff,Manhattan,Hell's Kitchen,40.757350,-73.993430,Entire home/apt,299,...,08-12-2023,2.09,1,0,27,No License,4.93,1,1,1
20756,782661008019550832,Rental unit in New York · ★5.0 · 1 bedroom · 1...,163083101,Marissa,Manhattan,Chinatown,40.713750,-73.991470,Entire home/apt,115,...,17-09-2023,0.91,1,363,7,No License,5,1,1,1
20757,566029911248687183,Rental unit in Queens · ★4.89 · 1 bedroom · 1 ...,93827372,Glenroy,Queens,Rosedale,40.658874,-73.728651,Private room,102,...,10-12-2023,4.50,1,0,62,OSE-STRREG-0000513,4.89,1,1,1

In [7]:
df.shape

(20758, 22)

In [8]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'rating',
       'bedrooms', 'beds', 'baths'],
      dtype='object')

In [9]:
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
number_of_reviews_ltm               int64
license                            object
rating                             object
bedrooms                           object
beds                                int64
baths                              object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   name                            20758 non-null  object
 2   host_id                         20758 non-null  int64
 3   host_name                       20758 non-null  object
 4   neighbourhood_group             20758 non-null  object
 5   neighbourhood                   20758 non-null  object
 6   latitude                        20758 non-null  float64
 7   longitude                       20758 non-null  float64
 8   room_type                       20758 non-null  object
 9   price                           20758 non-null  int64
 10  minimum_nights                  20758 non-null  int64
 11  number_of_reviews               20758 non-null  int64
 12  last_review                     20758 non-null  object
 13  reviews_per_month               20758 non-null  float64
 14  calculated_host_listings_count  20758 non-null  int64
 15  availability_365                20758 non-null  int64
 16  number_of_reviews_ltm           20758 non-null  int64
 17  license                         20758 non-null  object
 18  rating                          20758 non-null  object
 19  bedrooms                        20758 non-null  object
 20  beds                            20758 non-null  int64
 21  baths                           20758 non-null  object
dtypes: float64(3), int64(9), object(10)
memory usage: 3.5+ MB

In [11]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,beds
count,2.075800e+04,2.075800e+04,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000
mean,3.034044e+17,1.749316e+08,40.726798,-73.939161,187.776616,28.558435,42.642596,1.257910,18.844108,205.990317,10.852105,1.723721
std,3.901216e+17,1.725541e+08,0.060294,0.061403,1022.797208,33.536518,73.561654,1.904661,70.910834,135.087768,21.357071,1.212272
min,2.595000e+03,1.678000e+03,40.500314,-74.249840,10.000000,1.000000,1.000000,0.010000,1.000000,0.000000,0.000000,1.000000
25%,2.708808e+07,2.041738e+07,40.684150,-73.980710,80.000000,30.000000,4.000000,0.210000,1.000000,87.000000,1.000000,1.000000
50%,4.993003e+07,1.087271e+08,40.722820,-73.949587,125.000000,30.000000,14.000000,0.650000,2.000000,215.000000,3.000000,1.000000
75%,7.216019e+17,3.144102e+08,40.763098,-73.917460,199.000000,30.000000,49.000000,1.800000,5.000000,353.000000,15.000000,2.000000
max,1.054376e+18,5.504035e+08,40.911147,-73.713650,100000.000000,1250.000000,1865.000000,75.490000,713.000000,365.000000,1075.000000,42.000000

In [12]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
license                           0
rating                            0
bedrooms                          0
beds                              0
baths                             0
dtype: int64

In [13]:
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
number_of_reviews_ltm               int64
license                            object
rating                             object
bedrooms                           object
beds                                int64
baths                              object
dtype: object

In [14]:
df["bedrooms"]=pd.to_numeric(df["bedrooms"],errors="coerce")

In [15]:
df["baths"]=pd.to_numeric(df["baths"],errors="coerce")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   name                            20758 non-null  object
 2   host_id                         20758 non-null  int64
 3   host_name                       20758 non-null  object
 4   neighbourhood_group             20758 non-null  object
 5   neighbourhood                   20758 non-null  object
 6   latitude                        20758 non-null  float64
 7   longitude                       20758 non-null  float64
 8   room_type                       20758 non-null  object
 9   price                           20758 non-null  int64
 10  minimum_nights                  20758 non-null  int64
 11  number_of_reviews               20758 non-null  int64
 12  last_review                     20758 non-null  object
 13  reviews_per_month               20758 non-null  float64
 14  calculated_host_listings_count  20758 non-null  int64
 15  availability_365                20758 non-null  int64
 16  number_of_reviews_ltm           20758 non-null  int64
 17  license                         20758 non-null  object
 18  rating                          20758 non-null  object
 19  bedrooms                        18943 non-null  float64
 20  beds                            20758 non-null  int64
 21  baths                           20745 non-null  float64
dtypes: float64(5), int64(9), object(8)
memory usage: 3.5+ MB

In [18]:
df.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                                0
minimum_nights                       0
number_of_reviews                    0
last_review                          0
reviews_per_month                    0
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                              0
rating                               0
bedrooms                          1815
beds                                 0
baths                               13
dtype: int64

In [19]:
df["bedrooms"]=df["bedrooms"].fillna(df["bedrooms"].mean())

In [20]:
df["baths"]=df["baths"].fillna(df["baths"].mean())

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   name                            20758 non-null  object
 2   host_id                         20758 non-null  int64
 3   host_name                       20758 non-null  object
 4   neighbourhood_group             20758 non-null  object
 5   neighbourhood                   20758 non-null  object
 6   latitude                        20758 non-null  float64
 7   longitude                       20758 non-null  float64
 8   room_type                       20758 non-null  object
 9   price                           20758 non-null  int64
 10  minimum_nights                  20758 non-null  int64
 11  number_of_reviews               20758 non-null  int64
 12  last_review                     20758 non-null  object
 13  reviews_per_month               20758 non-null  float64
 14  calculated_host_listings_count  20758 non-null  int64
 15  availability_365                20758 non-null  int64
 16  number_of_reviews_ltm           20758 non-null  int64
 17  license                         20758 non-null  object
 18  rating                          20758 non-null  object
 19  bedrooms                        20758 non-null  float64
 20  beds                            20758 non-null  int64
 21  baths                           20758 non-null  float64
dtypes: float64(5), int64(9), object(8)
memory usage: 3.5+ MB

In [22]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
license                           0
rating                            0
bedrooms                          0
beds                              0
baths                             0
dtype: int64

In [23]:
df["rating"]=pd.to_numeric(df["rating"],errors="coerce")

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   name                            20758 non-null  object
 2   host_id                         20758 non-null  int64
 3   host_name                       20758 non-null  object
 4   neighbourhood_group             20758 non-null  object
 5   neighbourhood                   20758 non-null  object
 6   latitude                        20758 non-null  float64
 7   longitude                       20758 non-null  float64
 8   room_type                       20758 non-null  object
 9   price                           20758 non-null  int64
 10  minimum_nights                  20758 non-null  int64
 11  number_of_reviews               20758 non-null  int64
 12  last_review                     20758 non-null  object
 13  reviews_per_month               20758 non-null  float64
 14  calculated_host_listings_count  20758 non-null  int64
 15  availability_365                20758 non-null  int64
 16  number_of_reviews_ltm           20758 non-null  int64
 17  license                         20758 non-null  object
 18  rating                          17006 non-null  float64
 19  bedrooms                        20758 non-null  float64
 20  beds                            20758 non-null  int64
 21  baths                           20758 non-null  float64
dtypes: float64(6), int64(9), object(7)
memory usage: 3.5+ MB

In [25]:
df.to_csv("AB_NYC_Cleaned.csv", index=False)

In [27]:
df_cleaned=pd.read_csv("../data/AB_NYC_Cleaned.csv")
df_cleaned.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,7130382,Walter,Brooklyn,Clinton Hill,40.683710,-73.964610,Private room,55,...,20-12-2015,0.03,1,0,0,No License,5.00,1.000000,1,1.177995
1,45277537,Rental unit in New York · ★4.67 · 2 bedrooms ·...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.766610,-73.988100,Entire home/apt,144,...,01-05-2023,0.24,139,364,2,No License,4.67,2.000000,1,1.000000
2,971353993633883038,Rental unit in New York · ★4.17 · 1 bedroom · ...,528871354,Joshua,Manhattan,Chelsea,40.750764,-73.994605,Entire home/apt,187,...,18-12-2023,1.67,1,343,6,Exempt,4.17,1.000000,2,1.000000
3,3857863,Rental unit in New York · ★4.64 · 1 bedroom · ...,19902271,John And Catherine,Manhattan,Washington Heights,40.835600,-73.942500,Private room,120,...,17-09-2023,1.38,2,363,12,No License,4.64,1.000000,1,1.000000
4,40896611,Condo in New York · ★4.91 · Studio · 1 bed · 1...,61391963,Stay With Vibe,Manhattan,Murray Hill,40.751120,-73.978600,Entire home/apt,85,...,03-12-2023,0.24,133,335,3,No License,4.91,1.431927,1,1.000000

In [28]:
import os
os.listdir("../data")

['AB_NYC_2024.csv', 'AB_NYC_Cleaned.csv']

In [29]:
print("DATA CLEANING SUMMARY")
print("----------------------")
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

DATA CLEANING SUMMARY
----------------------
Total rows: 20758
Total columns: 22
Missing values: 3752
Duplicate rows: 0